### ISSUE TITLE
Add support for Rails 5.0

### ISSUE THREAD

**Issue by take-five** [take-five/activerecord-hierarchical_query#13]
Simply adding Rails 5.0 to dependency leads to broken tests.

**Comment by epaminond** [comment]
Are there any plans on Rails 5 support?

**Comment by walski** [comment]
Hey @epaminond et al, there is support for Rails 5 now through the `rails-5` and gem versions `>= 1.0.0` on rubygems.org

I've also put in a PR to update the Readme.
