### ISSUE TITLE
Column name 'parent' replaces automatically to 'parent_id'

### ISSUE THREAD

**Issue by green-ghost** [take-five/activerecord-hierarchical_query#17]
Schema:
```
  create_table "products", force: :cascade do |t|
    t.string   "title"
    t.text     "description"
    t.integer  "parent" #Foreign key
    t.boolean  "leaf"
  end
```

code:
` Product.join_recursive { start_with(parent: nil).connect_by(id: :parent).order_siblings(:title) }`

Error:
`PG::UndefinedColumn: ERROR:  column products.parent_id does not exist`

**Comment by take-five** [comment]
hi @green-ghost 

Could you also show me your `Product` model definition and erroneous SQL query?

**Comment by zachaysan** [comment]
I'm closing this issue due to lack of followup.
