### ISSUE TITLE
require statement

### ISSUE THREAD

**Issue by tinderfields** [take-five/activerecord-hierarchical_query#2]
Initially including the gemfile did not allow me to use the join_recursive function immediately in the console I had to do:

     require 'active_record/hierarchical_query'

**Comment by take-five** [comment]
Maybe you use old bundler version. Try to write in Gemfile:
```ruby
gem 'activerecord-hierarchical_query', require: 'active_record/hierarchical_query'
```

**Comment by lgebhardt** [comment]
I'm seeing the same issue using bundler 1.10.6. As you mention this works:

```ruby
gem 'activerecord-hierarchical_query', require: 'active_record/hierarchical_query'
```
