### ISSUE TITLE
LTree Support?

### ISSUE THREAD

**Issue by Un3qual** [take-five/activerecord-hierarchical_query#25]
Does this gem support LTree, and if not, are there plans to add support for it?

**Comment by take-five** [comment]
Currently there is no support for LTree and I didn't have plans to add it. But I'll happily accept pull requests from the community :)

**Comment by Un3qual** [comment]
Awesome. I'm gonna close this because I don't have time to work on it right now, but when I have time, I'll start working on it. 😄
