### ISSUE TITLE
pg ~>1.0 support

### ISSUE THREAD

**Issue by laiskajoonas** [take-five/activerecord-hierarchical_query#26]
Is there a specific reason why the pg dependency is set to ~> 0.21 in rails5 branch? The pg gem is at 1.1.3 currently.

**Comment by zachaysan** [comment]
Hey @laiskajoonas I knew [this issue](https://github.com/rails/rails/issues/31673) existed beforehand, but I had missed [this fix]. I'll try to upgrade the gem to the current version. 

Thanks for bringing this to my attention!

**Comment by zachaysan** [comment]
Thanks again @laiskajoonas I've fixed this in [1.1.0](https://rubygems.org/gems/activerecord-hierarchical_query/versions/1.1.0), which is currently on the rails-5-upcoming branch, but will be merged into master over the next week or two.
