### ISSUE TITLE
PG 1.2.x Support

### ISSUE THREAD

**Issue by xtagon** [take-five/activerecord-hierarchical_query#29]
Hi,

I'd like to start using PG 1.2, and found this incompatibility:

```
Bundler could not find compatible versions for gem "pg":
  In Gemfile:
    pg (~> 1.2)

    activerecord-hierarchical_query (= 1.2.2) was resolved to 1.2.2, which depends on
      pg (< 1.2, >= 0.21)
```

Could activerecord-hierarchical_query be updated to support pg 1.2? I'm happy to help if needed, but I thought I'd bring it up in an issue first.

Thanks, and happy new year!

**Comment by zachaysan** [comment]
I'm just about to go to bed but I'll run the test suite early tomorrow. Usually this type of upgrade is easy. Thanks for creating the issue!

**Comment by zachaysan** [comment]
And of course! Happy New Year to you too!

**Comment by zachaysan** [comment]
Ok I pushed the new gem. The tests pass with pg 1.2 but I didn't get a chance to test the new gem in an actual rails project so if you run into issues please let me know. Have a great day and thanks for opening the issue!

**Comment by xtagon** [comment]
Thanks, I'll try it!
