### ISSUE TITLE
pg-1.4

### ISSUE THREAD

**Issue by mkamensky** [take-five/activerecord-hierarchical_query#37]
Is there a reason to not support it? Thanks

**Comment by zachaysan** [comment]
Should be simple enough to pull the project, update it, and run the test suite. Would be an easy contribution if it works @lholden

**Comment by lholden** [comment]
Someone else has already done this :) https://github.com/take-five/activerecord-hierarchical_query/pull/38

**Comment by zachaysan** [comment]
Gem published! Had to brush off my ruby haha :)

https://rubygems.org/gems/activerecord-hierarchical_query/versions/1.4.2
